// Seed Wardrobe: 86 item cosmetic import từ Avatar (items table) + pet/mount tự thêm.
// Tất cả mua bằng coin. Slot phân loại theo tên + zorder.
import { PrismaClient, AvatarSlot } from '@prisma/client';
const prisma = new PrismaClient();

const clothes = [
  {
    "slug": "av-tr-n",
    "name": "tròn",
    "slot": "HAIR",
    "gender": 0,
    "priceCoin": 15000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 30,
    "sortOrder": 0,
    "asset": null
  },
  {
    "slug": "av-d-ng-ng",
    "name": "dựng đứng",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 1,
    "asset": null
  },
  {
    "slug": "av-s-mi",
    "name": "sơ mi",
    "slot": "TOP",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 2,
    "asset": null
  },
  {
    "slug": "av-short",
    "name": "short",
    "slot": "BOTTOM",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 3,
    "asset": null
  },
  {
    "slug": "av-en",
    "name": "đen",
    "slot": "HAIR",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 4,
    "asset": null
  },
  {
    "slug": "av-mat-buon",
    "name": "Mat Buon",
    "slot": "FACE",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 5,
    "asset": null
  },
  {
    "slug": "av-mat-vui",
    "name": "Mat Vui",
    "slot": "FACE",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 6,
    "asset": null
  },
  {
    "slug": "av-mat-nhay",
    "name": "Mat nhay",
    "slot": "FACE",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 7,
    "asset": null
  },
  {
    "slug": "av-mat-gian",
    "name": "Mat gian",
    "slot": "FACE",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 8,
    "asset": null
  },
  {
    "slug": "av-mat-khoc",
    "name": "Mat khoc",
    "slot": "FACE",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 9,
    "asset": null
  },
  {
    "slug": "av-mat-cuoi-to",
    "name": "Mat cuoi to",
    "slot": "FACE",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 10,
    "asset": null
  },
  {
    "slug": "av-mat-le-luoi",
    "name": "Mat le luoi",
    "slot": "FACE",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 11,
    "asset": null
  },
  {
    "slug": "av-mat-xau-ho",
    "name": "Mat xau ho",
    "slot": "FACE",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 12,
    "asset": null
  },
  {
    "slug": "av-xanh",
    "name": "xanh",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 5000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 13,
    "asset": null
  },
  {
    "slug": "av-tr-con",
    "name": "trẻ con",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 14,
    "asset": null
  },
  {
    "slug": "av-si-u-nh-n",
    "name": "siêu nhân",
    "slot": "TOP",
    "gender": 1,
    "priceCoin": 31000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 15,
    "asset": null
  },
  {
    "slug": "av-si-u-nh-n-2",
    "name": "siêu nhân",
    "slot": "BOTTOM",
    "gender": 1,
    "priceCoin": 31000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 16,
    "asset": null
  },
  {
    "slug": "av-bong-b-ng-30-ng-y",
    "name": "bong bóng(30 ngày)",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 500,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 70,
    "sortOrder": 17,
    "asset": null
  },
  {
    "slug": "av-k-o-b-c-h-30-ng-y",
    "name": "kẹo bạc hà(30 ngày)",
    "slot": "HAIR",
    "gender": 0,
    "priceCoin": 500,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 70,
    "sortOrder": 18,
    "asset": null
  },
  {
    "slug": "av-hoa-30-ng-y",
    "name": "hoa(30 ngày)",
    "slot": "HAIR",
    "gender": 0,
    "priceCoin": 500,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 70,
    "sortOrder": 19,
    "asset": null
  },
  {
    "slug": "av-mat-chay-mau",
    "name": "Mat chay mau",
    "slot": "FACE",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 20,
    "asset": null
  },
  {
    "slug": "av-b-p-b",
    "name": "búp bê",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 21,
    "asset": null
  },
  {
    "slug": "av-nh-nh-nh",
    "name": "nhí nhảnh",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 5000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 22,
    "asset": null
  },
  {
    "slug": "av-b-ch-tuy-t",
    "name": "bạch tuyết",
    "slot": "TOP",
    "gender": 2,
    "priceCoin": 20000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 23,
    "asset": null
  },
  {
    "slug": "av-b-ch-tuy-t-2",
    "name": "bạch tuyết",
    "slot": "BOTTOM",
    "gender": 2,
    "priceCoin": 20000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 24,
    "asset": null
  },
  {
    "slug": "av-thun-n",
    "name": "thun nữ",
    "slot": "TOP",
    "gender": 2,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 25,
    "asset": null
  },
  {
    "slug": "av-c-t-nh",
    "name": "cá tính",
    "slot": "BOTTOM",
    "gender": 2,
    "priceCoin": 5000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 26,
    "asset": null
  },
  {
    "slug": "av-t-i-t-n",
    "name": "tươi tắn",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 6000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 27,
    "asset": null
  },
  {
    "slug": "av-g-i-c-m",
    "name": "gợi cảm",
    "slot": "TOP",
    "gender": 2,
    "priceCoin": 6000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 28,
    "asset": null
  },
  {
    "slug": "av-m-a-h",
    "name": "mùa hè",
    "slot": "BOTTOM",
    "gender": 2,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 29,
    "asset": null
  },
  {
    "slug": "av-l-m-l-nh",
    "name": "lém lỉnh",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 27600,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 30,
    "asset": null
  },
  {
    "slug": "av-th-s-n",
    "name": "thợ săn",
    "slot": "TOP",
    "gender": 1,
    "priceCoin": 15000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 31,
    "asset": null
  },
  {
    "slug": "av-th-s-n-2",
    "name": "thợ săn",
    "slot": "BOTTOM",
    "gender": 1,
    "priceCoin": 15000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 32,
    "asset": null
  },
  {
    "slug": "av-xanh-ng-c-b-ch",
    "name": "xanh ngọc bích",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 75000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 33,
    "asset": null
  },
  {
    "slug": "av-h-ng-d-th-ng",
    "name": "hồng dễ thương",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 34,
    "asset": null
  },
  {
    "slug": "av-t-m-nh-t",
    "name": "tím nhạt",
    "slot": "HAIR",
    "gender": 0,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 35,
    "asset": null
  },
  {
    "slug": "av-n-u",
    "name": "nâu",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 2000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 36,
    "asset": null
  },
  {
    "slug": "av-qu-t-c",
    "name": "quý tộc",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 2000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 37,
    "asset": null
  },
  {
    "slug": "av-qu-t-c-2",
    "name": "quý tộc",
    "slot": "TOP",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 38,
    "asset": null
  },
  {
    "slug": "av-qu-t-c-3",
    "name": "quý tộc",
    "slot": "BOTTOM",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 39,
    "asset": null
  },
  {
    "slug": "av-l-ch-l-m",
    "name": "lịch lãm",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 32000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 40,
    "asset": null
  },
  {
    "slug": "av-comple-l-ch-l-m",
    "name": "comple lịch lãm",
    "slot": "TOP",
    "gender": 1,
    "priceCoin": 48000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 41,
    "asset": null
  },
  {
    "slug": "av-comple-l-ch-l-m-2",
    "name": "comple lịch lãm",
    "slot": "BOTTOM",
    "gender": 1,
    "priceCoin": 48000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 42,
    "asset": null
  },
  {
    "slug": "av-thi-n-nhi-n",
    "name": "thiên nhiên",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 43,
    "asset": null
  },
  {
    "slug": "av-d-n-t-c",
    "name": "dân tộc",
    "slot": "TOP",
    "gender": 2,
    "priceCoin": 20000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 44,
    "asset": null
  },
  {
    "slug": "av-d-n-t-c-2",
    "name": "dân tộc",
    "slot": "BOTTOM",
    "gender": 2,
    "priceCoin": 20000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 45,
    "asset": null
  },
  {
    "slug": "av-hi-n-i",
    "name": "hiện đại",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 157500,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 46,
    "asset": null
  },
  {
    "slug": "av-b-o-m-u",
    "name": "bảo mẫu",
    "slot": "TOP",
    "gender": 2,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 47,
    "asset": null
  },
  {
    "slug": "av-b-o-m-u-2",
    "name": "bảo mẫu",
    "slot": "BOTTOM",
    "gender": 2,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 48,
    "asset": null
  },
  {
    "slug": "av-d-th-ng",
    "name": "dễ thương",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 49,
    "asset": null
  },
  {
    "slug": "av-h-c-sinh",
    "name": "học sinh",
    "slot": "TOP",
    "gender": 2,
    "priceCoin": 20000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 50,
    "asset": null
  },
  {
    "slug": "av-h-c-sinh-2",
    "name": "học sinh",
    "slot": "BOTTOM",
    "gender": 2,
    "priceCoin": 20000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 51,
    "asset": null
  },
  {
    "slug": "av-s-nh-i-u",
    "name": "sành điệu",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 52,
    "asset": null
  },
  {
    "slug": "av-s-nh-i-u-2",
    "name": "sành điệu",
    "slot": "TOP",
    "gender": 1,
    "priceCoin": 29500,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 53,
    "asset": null
  },
  {
    "slug": "av-s-nh-i-u-3",
    "name": "sành điệu",
    "slot": "BOTTOM",
    "gender": 1,
    "priceCoin": 29500,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 54,
    "asset": null
  },
  {
    "slug": "av-hi-n-i-2",
    "name": "hiện đại",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 95000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 55,
    "asset": null
  },
  {
    "slug": "av-ti-n-s",
    "name": "tiến sĩ",
    "slot": "TOP",
    "gender": 0,
    "priceCoin": 5000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 56,
    "asset": null
  },
  {
    "slug": "av-ti-n-s-2",
    "name": "tiến sĩ",
    "slot": "BOTTOM",
    "gender": 0,
    "priceCoin": 5000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 57,
    "asset": null
  },
  {
    "slug": "av-v-s",
    "name": "võ sĩ",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 58,
    "asset": null
  },
  {
    "slug": "av-v-s-2",
    "name": "võ sĩ",
    "slot": "TOP",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 59,
    "asset": null
  },
  {
    "slug": "av-v-s-3",
    "name": "võ sĩ",
    "slot": "BOTTOM",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 60,
    "asset": null
  },
  {
    "slug": "av-tr-trung",
    "name": "trẻ trung",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 43000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 61,
    "asset": null
  },
  {
    "slug": "av-ph-p-s",
    "name": "pháp sư",
    "slot": "TOP",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 62,
    "asset": null
  },
  {
    "slug": "av-ph-p-s-2",
    "name": "pháp sư",
    "slot": "BOTTOM",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 63,
    "asset": null
  },
  {
    "slug": "av-minh-tinh",
    "name": "minh tinh",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 64,
    "asset": null
  },
  {
    "slug": "av-d-h-i",
    "name": "dạ hội",
    "slot": "TOP",
    "gender": 2,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 65,
    "asset": null
  },
  {
    "slug": "av-d-h-i-2",
    "name": "dạ hội",
    "slot": "BOTTOM",
    "gender": 2,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 66,
    "asset": null
  },
  {
    "slug": "av-c-t-nh-2",
    "name": "cá tính",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 67,
    "asset": null
  },
  {
    "slug": "av-nh-t-b-n",
    "name": "Nhật Bản",
    "slot": "TOP",
    "gender": 2,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 68,
    "asset": null
  },
  {
    "slug": "av-nh-t-b-n-2",
    "name": "Nhật Bản",
    "slot": "BOTTOM",
    "gender": 2,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 69,
    "asset": null
  },
  {
    "slug": "av-samurai",
    "name": "samurai",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 70,
    "asset": null
  },
  {
    "slug": "av-samurai-2",
    "name": "samurai",
    "slot": "TOP",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 71,
    "asset": null
  },
  {
    "slug": "av-samurai-3",
    "name": "samurai",
    "slot": "BOTTOM",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 72,
    "asset": null
  },
  {
    "slug": "av-hi-p-s",
    "name": "hiệp sĩ",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 73,
    "asset": null
  },
  {
    "slug": "av-hi-p-s-2",
    "name": "hiệp sĩ",
    "slot": "TOP",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 74,
    "asset": null
  },
  {
    "slug": "av-hi-p-s-3",
    "name": "hiệp sĩ",
    "slot": "BOTTOM",
    "gender": 1,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 75,
    "asset": null
  },
  {
    "slug": "av-h-n-nhi-n",
    "name": "hồn nhiên",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 50,
    "sortOrder": 76,
    "asset": null
  },
  {
    "slug": "av-h-n-nhi-n-2",
    "name": "hồn nhiên",
    "slot": "TOP",
    "gender": 2,
    "priceCoin": 5000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 20,
    "sortOrder": 77,
    "asset": null
  },
  {
    "slug": "av-h-n-nhi-n-3",
    "name": "hồn nhiên",
    "slot": "BOTTOM",
    "gender": 2,
    "priceCoin": 5000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 10,
    "sortOrder": 78,
    "asset": null
  },
  {
    "slug": "av-n-u-2",
    "name": "nâu",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 79,
    "asset": null
  },
  {
    "slug": "av-xanh-n-c-bi-n",
    "name": "xanh nước biển",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 20000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 80,
    "asset": null
  },
  {
    "slug": "av-t-m",
    "name": "tím",
    "slot": "HAIR",
    "gender": 2,
    "priceCoin": 10000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 81,
    "asset": null
  },
  {
    "slug": "av-xanh-n-c-bi-n-2",
    "name": "xanh nước biển",
    "slot": "HAIR",
    "gender": 1,
    "priceCoin": 20000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 82,
    "asset": null
  },
  {
    "slug": "av-v-ng",
    "name": "vàng",
    "slot": "HAIR",
    "gender": 0,
    "priceCoin": 6000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 83,
    "asset": null
  },
  {
    "slug": "av-item",
    "name": "đỏ",
    "slot": "HAIR",
    "gender": 0,
    "priceCoin": 1000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 40,
    "sortOrder": 84,
    "asset": null
  },
  {
    "slug": "av-m-p",
    "name": "mập",
    "slot": "HAIR",
    "gender": 0,
    "priceCoin": 15000,
    "reqLevel": 0,
    "expiredDay": 0,
    "zorder": 30,
    "sortOrder": 85,
    "asset": null
  }
];

// Pet & Mount tự thêm (dump không có). Pet dùng icon vật nuôi nông trại cho phù hợp.
const pets = [
  { slug: 'pet-ga', name: 'Gà con', slot: 'PET', gender: 0, priceCoin: 8000, reqLevel: 1, expiredDay: 0, zorder: 5, asset: '/game-assets/nongtrai/vatnuoi/50-con.gif', sortOrder: 1 },
  { slug: 'pet-cho', name: 'Cún cưng', slot: 'PET', gender: 0, priceCoin: 15000, reqLevel: 2, expiredDay: 0, zorder: 5, asset: '/game-assets/nongtrai/img/icon/animal.png', sortOrder: 2 },
  { slug: 'pet-lon', name: 'Heo con', slot: 'PET', gender: 0, priceCoin: 12000, reqLevel: 2, expiredDay: 0, zorder: 5, asset: '/game-assets/nongtrai/vatnuoi/51-con.gif', sortOrder: 3 },
  { slug: 'pet-bo', name: 'Bê con', slot: 'PET', gender: 0, priceCoin: 20000, reqLevel: 4, expiredDay: 0, zorder: 5, asset: '/game-assets/nongtrai/vatnuoi/52-con.gif', sortOrder: 4 },
  { slug: 'pet-cuu', name: 'Cừu non', slot: 'PET', gender: 0, priceCoin: 18000, reqLevel: 4, expiredDay: 0, zorder: 5, asset: '/game-assets/nongtrai/vatnuoi/53-con.gif', sortOrder: 5 },
  { slug: 'pet-ca', name: 'Cá vàng', slot: 'PET', gender: 0, priceCoin: 6000, reqLevel: 1, expiredDay: 0, zorder: 5, asset: '/game-assets/cauca/1.png', sortOrder: 6 },
];

const mounts = [
  { slug: 'mount-ngua', name: 'Ngựa thường', slot: 'MOUNT', gender: 0, priceCoin: 50000, reqLevel: 5, expiredDay: 0, zorder: 1, asset: '/game-assets/nongtrai/vatnuoi/54.gif', sortOrder: 1 },
  { slug: 'mount-trau', name: 'Trâu cày', slot: 'MOUNT', gender: 0, priceCoin: 40000, reqLevel: 5, expiredDay: 0, zorder: 1, asset: '/game-assets/nongtrai/vatnuoi/52.gif', sortOrder: 2 },
  { slug: 'mount-bo-vang', name: 'Bò vàng', slot: 'MOUNT', gender: 0, priceCoin: 80000, reqLevel: 10, expiredDay: 0, zorder: 1, asset: '/game-assets/nongtrai/img/icon/animal.png', sortOrder: 3 },
];

async function main() {
  const all = [...clothes, ...pets, ...mounts];
  for (const it of all) {
    const data = { ...it, slot: it.slot as AvatarSlot, asset: (it as any).asset ?? null };
    await prisma.avatarItemTemplate.upsert({ where: { slug: it.slug }, update: data, create: data });
  }
  console.log(`Seeded wardrobe: ${clothes.length} clothes, ${pets.length} pets, ${mounts.length} mounts`);
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());

